# Generated by Django 5.2 on 2025-06-18 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manicuristas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ausente', 'Ausente'), ('tardanza', 'Tardanza')], max_length=10)),
                ('tipo_ausencia', models.CharField(blank=True, choices=[('completa', 'Día Completo'), ('por_horas', 'Por Horas')], max_length=10, null=True)),
                ('hora_inicio_ausencia', models.TimeField(blank=True, null=True)),
                ('hora_fin_ausencia', models.TimeField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('manicurista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manicuristas.manicurista')),
            ],
            options={
                'verbose_name_plural': 'Novedades',
                'ordering': ['-fecha', '-created_at'],
                'unique_together': {('manicurista', 'fecha')},
            },
        ),
    ]
