# Generated by Django 5.2 on 2025-06-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='fecha',
            field=models.DateField(),
        ),
    ]
