# Generated by Django 5.2 on 2025-07-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_alter_novedad_fecha'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='novedad',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='novedad',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='novedad',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='estado',
            field=models.CharField(choices=[('ausente', 'Ausente'), ('tardanza', 'Tardanza'), ('anulada', 'Anulada')], max_length=10),
        ),
    ]
