# Generated by Django 5.2 on 2025-07-21 02:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicuristas', '0003_manicurista_especialidad'),
        ('novedades', '0003_alter_novedad_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novedad',
            options={'ordering': ['-fecha', 'manicurista__nombre'], 'verbose_name': 'Novedad', 'verbose_name_plural': 'Novedades'},
        ),
        migrations.RenameField(
            model_name='novedad',
            old_name='updated_at',
            new_name='fecha_actualizacion',
        ),
        migrations.RenameField(
            model_name='novedad',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='novedad',
            old_name='motivo',
            new_name='observaciones',
        ),
        migrations.AlterUniqueTogether(
            name='novedad',
            unique_together={('manicurista', 'fecha')},
        ),
        migrations.AlterField(
            model_name='novedad',
            name='estado',
            field=models.CharField(choices=[('normal', 'Normal'), ('tardanza', 'Tardanza'), ('ausente', 'Ausente'), ('anulada', 'Anulada')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='manicurista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='manicuristas.manicurista'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='tipo_ausencia',
            field=models.CharField(blank=True, choices=[('completa', 'Día Completo'), ('por_horas', 'Por Horas')], max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='novedad',
            name='hora_salida',
        ),
    ]
