# Generated by Django 5.2 on 2025-06-18 06:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraHasInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='compras.compra')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.insumo')),
            ],
            options={
                'verbose_name': 'Compra - Insumo',
                'verbose_name_plural': 'Compras - Insumos',
            },
        ),
    ]
