# Generated by Django 5.2 on 2025-06-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicuristas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manicurista',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Manicure Clásica', 'Manicure Clásica'), ('Manicure Francesa', 'Manicure Francesa'), ('Manicure Gel', 'Manicure Gel'), ('Manicure Acrílica', 'Manicure Acrílica'), ('Nail Art', 'Nail Art'), ('Pedicure', 'Pedicure'), ('Uñas Esculpidas', 'Uñas Esculpidas'), ('Decoración de Uñas', 'Decoración de Uñas'), ('Manicure Express', 'Manicure Express'), ('Tratamientos de Cutículas', 'Tratamientos de Cutículas')], help_text='Especialidad principal de la manicurista', max_length=50, null=True),
        ),
    ]
