# Generated by Django 5.2 on 2025-06-24 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='citascompletadas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='50% del total de servicios completados en el período', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Citas Completadas'),
        ),
    ]
