# Generated by Django 5.2 on 2025-07-08 14:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0003_liquidacion_citascompletadas'),
        ('manicuristas', '0003_manicurista_especialidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liquidacion',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Liquidación', 'verbose_name_plural': 'Liquidaciones'},
        ),
        migrations.RenameField(
            model_name='liquidacion',
            old_name='updated_at',
            new_name='fecha_actualizacion',
        ),
        migrations.RenameField(
            model_name='liquidacion',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.AlterUniqueTogether(
            name='liquidacion',
            unique_together={('manicurista', 'fecha_inicio', 'fecha_final')},
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='bonificacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bonificación adicional', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='fecha_final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='manicurista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='manicuristas.manicurista'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Valor base de la liquidación', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterModelTable(
            name='liquidacion',
            table='liquidaciones',
        ),
        migrations.RemoveField(
            model_name='liquidacion',
            name='citascompletadas',
        ),
    ]
