# Generated by Django 5.2 on 2025-07-11 13:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('manicuristas', '0003_manicurista_especialidad'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='duracion_total',
            field=models.PositiveIntegerField(default=0, help_text='Duración total de todos los servicios en minutos', verbose_name='Duración total (minutos)'),
        ),
        migrations.AddField(
            model_name='cita',
            name='manicurista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manicuristas.manicurista', verbose_name='Manicurista'),
        ),
        migrations.AddField(
            model_name='cita',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio total de todos los servicios', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio total de la cita'),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(blank=True, help_text='Servicio principal (para compatibilidad)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_principal', to='servicios.servicio', verbose_name='Servicio Principal'),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicios',
            field=models.ManyToManyField(blank=True, help_text='Servicios incluidos en la cita', to='servicios.servicio', verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='duracion_estimada',
            field=models.PositiveIntegerField(blank=True, help_text='Duración del servicio principal (para compatibilidad)', null=True, verbose_name='Duración estimada (minutos)'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='precio_servicio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio del servicio principal (para compatibilidad)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio del servicio principal'),
        ),
    ]
