# Generated by Django 5.2 on 2025-07-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_duracion_total_cita_manicurista_and_more'),
    ]

    operations = [
    ]
