# Generated by Django 5.2 on 2025-07-11 14:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_recreate_created_at'),
        ('manicuristas', '0003_manicurista_especialidad'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='duracion_estimada',
            field=models.PositiveIntegerField(help_text='Duración del servicio principal (para compatibilidad)', verbose_name='Duración estimada (minutos)'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='manicurista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manicuristas.manicurista', verbose_name='Manicurista'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='precio_servicio',
            field=models.DecimalField(decimal_places=2, help_text='Precio del servicio principal (para compatibilidad)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio del servicio principal'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(help_text='Servicio principal (para compatibilidad)', on_delete=django.db.models.deletion.CASCADE, related_name='citas_principal', to='servicios.servicio', verbose_name='Servicio Principal'),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('manicurista', 'fecha_cita', 'hora_cita')},
        ),
    ]
