# Generated by Django 5.2 on 2025-07-21 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_cita_duracion_estimada_alter_cita_manicurista_and_more'),
        ('novedades', '0004_alter_novedad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelación'),
        ),
        migrations.AddField(
            model_name='cita',
            name='novedad_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_afectadas', to='novedades.novedad', verbose_name='Novedad Relacionada'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('cancelada_por_novedad', 'Cancelada por Novedad')], default='pendiente', max_length=30, verbose_name='Estado'),
        ),
    ]
