# Generated by Django 5.2 on 2025-07-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_estado_cliente_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contraseña_temporal',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='debe_cambiar_contraseña',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo_electronico',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
