# Generated by Django 5.2 on 2025-07-11 13:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_duracion_total_cita_manicurista_and_more'),
        ('ventaservicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaservicio',
            name='citas',
            field=models.ManyToManyField(blank=True, help_text='Citas asociadas a esta venta', to='citas.cita', verbose_name='Citas relacionadas'),
        ),
        migrations.AlterField(
            model_name='ventaservicio',
            name='cita',
            field=models.ForeignKey(blank=True, help_text='Cita principal (para compatibilidad)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_principal', to='citas.cita', verbose_name='Cita principal'),
        ),
        migrations.AlterField(
            model_name='ventaservicio',
            name='fecha_venta',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de venta'),
        ),
        migrations.AlterField(
            model_name='ventaservicio',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='ventaservicio',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio unitario'),
        ),
    ]
