# Generated by Django 5.2 on 2025-07-17 22:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('ventaservicios', '0003_alter_detalleventaservicio_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventaservicio',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='ventaservicio',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ventaservicio',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento aplicado'),
        ),
        migrations.AlterField(
            model_name='ventaservicio',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='ventaservicio',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicio', verbose_name='Servicio principal (compatibilidad)'),
        ),
        migrations.AlterField(
            model_name='ventaservicio',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
    ]
