# Generated by Django 5.2 on 2025-07-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='cantidad_minima',
        ),
    ]
