# Generated by Django 5.2 on 2025-07-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Anulación'),
        ),
    ]
