name: Test API (Python)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: winespaapi
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost -u root -p1234" --health-interval=30s --health-timeout=10s --health-retries=5

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verificar configuración Django
        run: |
          python -c "import django; print('Django version:', django.get_version())"
        env:
          DJANGO_SETTINGS_MODULE: winespa.settings
          PYTHONPATH: ${{ github.workspace }}
          DB_NAME: winespaapi
          DB_USER: root
          DB_PASSWORD: 1234
          DB_HOST: 127.0.0.1
          DB_PORT: 3306

      - name: Esperar MySQL
        run: |
          echo "Esperando que MySQL esté listo..."
          sleep 30
          echo "MySQL debería estar listo ahora"

      - name: Verificar conexión MySQL
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -p1234 -e "SELECT VERSION();"
          echo "Conexión a MySQL exitosa"

      - name: Verificar base de datos de prueba
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -p1234 -e "SHOW DATABASES;"
          echo "Base de datos de prueba configurada correctamente"

      - name: Configurar base de datos Django
        run: |
          python manage.py migrate --run-syncdb
        env:
          DJANGO_SETTINGS_MODULE: winespa.settings
          PYTHONPATH: ${{ github.workspace }}
          DEBUG: "True"
          DB_NAME: winespaapi
          DB_USER: root
          DB_PASSWORD: 1234
          DB_HOST: 127.0.0.1
          DB_PORT: 3306

      - name: Ejecutar pruebas
        run: |
          python -m pytest api/tests/ -v --reuse-db --create-db
        env:
          DJANGO_SETTINGS_MODULE: winespa.settings
          PYTHONPATH: ${{ github.workspace }}
          DEBUG: "True"
          DB_NAME: winespaapi
          DB_USER: root
          DB_PASSWORD: 1234
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
